Move predicate_label examples to predicate_id in sssom_schema.yaml
mapping-commons/sssom pull request #370
Opened 2024-07-04 11:26 UTC by matentzn

Fixes #369.

The examples for the predicate_id slot where in the wrong slot (predicate_label), here we move them to be correct.

I have also added a single example for the predicate_label slot.

- [X] `docs/` have been added/updated if necessary
- [ ] `make test` has been run locally
- [ ] tests have been added/updated (if applicable)
- [ ] [CHANGELOG.md](https://github.com/mapping-commons/sssom/blob/master/CHANGELOG.md) has been updated.

If you are proposing a change to the SSSOM metadata model, you must 

- [ ] provide a full, working and valid example in `examples/`
- [ ] provide a link to the related GitHub issue in the `see_also` field of the linkml model
- [ ] provide a link to a valid example in the `see_also` field of the linkml model

2024-07-04 21:08 UTC, joeflack4 approved these changes

2024-07-04 21:08 UTC, joeflack4 commented on src/sssom_schema/schema/sssom_schema.yaml
> +    description: A modifier for negating the prediate. See https://github.com/mapping-commons/sssom/issues/40 for discussion
```suggestion
    description: A modifier for negating the predicate. See https://github.com/mapping-commons/sssom/issues/40 for discussion
```

2024-07-04 21:08 UTC, joeflack4 commented on src/sssom_schema/schema/sssom_schema.yaml
>      examples:
LGTM!

2024-08-03 05:16 UTC, ehartley approved these changes
Looks good to me.

2024-08-03 19:57 UTC, joeflack4 approved these changes

2024-08-05 01:14 UTC, hrshdhgd requested changes
run `make all` ... same as https://github.com/mapping-commons/sssom/pull/386#pullrequestreview-2217867625

2024-08-06 13:49 UTC, merged